version: '3'

services:
  parakeet-server:
    image: nginx
    container_name: 'parakeet-container'
    volumes:
      - ./parakeet-server:/usr/share/nginx/html
    ports:
      - 7002:80
  
  sparrow-server:
    image: nginx
    container_name: 'sparrow-container'
    volumes:
      - ./sparrow-server:/usr/share/nginx/html
    ports:
      - 7001:80

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80